services:
  db:
    image: postgres:15-alpine
    container_name: oldshop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: oldshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: oldshop_backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=oldshop
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./database:/app/database # Ánh xạ trái tim DB vào đây

volumes:
  postgres_data: