sonar.projectKey=oldshop-ecommerce
# Thay dòng dưới bằng tên Organization của bạn trên SonarCloud
sonar.organization=tranhoangdatsc
sonar.projectName=Oldshop Ecommerce

# 1. Mã nguồn nằm ở đâu?
sonar.sources=backend/app, frontend/src
sonar.exclusions=**/node_modules/**, **/venv/**, frontend/src/assets/**, **/*.spec.ts, **/*.mock.ts

# 2. File test nằm ở đâu?
sonar.tests=backend/tests, frontend/src
sonar.test.inclusions=**/*.spec.ts, backend/tests/**/*.py

# 3. File coverage Backend nằm ở đâu?
sonar.python.coverage.reportPaths=backend/coverage.xml

# 4. File coverage Frontend nằm ở đâu? (Dùng ** để tự dò thư mục con)
sonar.javascript.lcov.reportPaths=frontend/coverage/**/lcov.info