[pytest]
addopts = -p no:warnings --cov=app --cov-report=xml:coverage.xml
filterwarnings =
    ignore::DeprecationWarning
    ignore::sqlalchemy.exc.SAWarning
    ignore::pydantic.PydanticDeprecatedSince20